// Data
export const products = [
  {
    productImg: "..//images/phone-1.webp",
    productName: "Iphone 13 Pro Max",
    productCost: "1100 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/phone-2.webp",
    productName: "Iphone 11",
    productCost: "1400 $",
    viewed: "12k",
    purchesed: "159",
  },
  {
    productImg: "..//images/phone-3.webp",
    productName: "Iphone 12 Pro Max",
    productCost: "1300 $",
    viewed: "11k",
    purchesed: "304",
  },
  {
    productImg: "..//images/phone-1.webp",
    productName: "Iphone 14 Pro Max",
    productCost: "1250 $",
    viewed: "32k",
    purchesed: "149",
  },
  {
    productImg: "..//images/phone-2.webp",
    productName: "Iphone 11",
    productCost: "1500 $",
    viewed: "5k",
    purchesed: "109",
  },
  {
    productImg: "..//images/phone-3.webp",
    productName: "Iphone 10",
    productCost: "1600 $",
    viewed: "9k",
    purchesed: "188",
  },
  {
    productImg: "..//images/watch-1.png",
    productName: "Apple watch SE GBS",
    productCost: "299.99 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/watch-2.png",
    productName: "Apple watch",
    productCost: "250 $",
    viewed: "2k",
    purchesed: "238",
  },
  {
    productImg: "..//images/watch-3.png",
    productName: "Apple watch SE GBS",
    productCost: "340 $",
    viewed: "5k",
    purchesed: "128",
  },
  {
    productImg: "..//images/watch-4.png",
    productName: "Apple watch",
    productCost: "350 $",
    viewed: "10k",
    purchesed: "98",
  },
  {
    productImg: "..//images/watch-5.webp",
    productName: "Apple watch SE GBS",
    productCost: "160 $",
    viewed: "11k",
    purchesed: "218",
  },
  {
    productImg: "..//images/watch-6.webp",
    productName: "Apple watch SE GBS",
    productCost: "275 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/airpod-1.webp",
    productName: "Apple Airpod Pro HK",
    productCost: "450 $",
    viewed: "18k",
    purchesed: "78",
  },
  {
    productImg: "..//images/airpod-2.png",
    productName: "Apple Airpod Pro",
    productCost: "367 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/airpod-3.png",
    productName: "Apple Airpod Pro HK",
    productCost: "378 $",
    viewed: "7k",
    purchesed: "109",
  },
  {
    productImg: "..//images/airpod-4.png",
    productName: "Apple Airpod",
    productCost: "320 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/airpod-5.png",
    productName: "Apple Airpod HK",
    productCost: "190 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/airpod-6.png",
    productName: "Apple Airpod Pro HK",
    productCost: "570 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/mac-1.png",
    productName: "Mac Book Air Pro",
    productCost: "1745 $",
    viewed: "7k",
    purchesed: "18",
  },
  {
    productImg: "..//images/mac-2.png",
    productName: "Mac Book M1",
    productCost: "1300 $",
    viewed: "7k",
    purchesed: "88",
  },
  {
    productImg: "..//images/mac-3.png",
    productName: "Mac Book Air M2",
    productCost: "1700 $",
    viewed: "8k",
    purchesed: "19",
  },
  {
    productImg: "..//images/mac-4.png",
    productName: "Mac Book Air",
    productCost: "1650 $",
    viewed: "7k",
    purchesed: "298",
  },
  {
    productImg: "..//images/mac-5.png",
    productName: "Mac Book Air Pro",
    productCost: "1550 $",
    viewed: "18k",
    purchesed: "14",
  },
  {
    productImg: "..//images/mac-2.png",
    productName: "Mac Book Air M1",
    productCost: "1850 $",
    viewed: "19k",
    purchesed: "29",
  },
];
// Data
